# Generated by Django 4.0.4 on 2022-05-11 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0004_alter_changeinexpenses_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 37, 34, 538898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 37, 34, 538371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 37, 34, 539531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='onetimeinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 37, 34, 540049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recurringinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 37, 34, 540594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 37, 34, 537795, tzinfo=utc)),
        ),
    ]
