# Generated by Django 4.0.4 on 2022-05-11 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0005_alter_changeinexpenses_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 42, 31, 61606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 42, 31, 61011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 42, 31, 62267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='onetimeinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 42, 31, 62803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recurringinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 42, 31, 63350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 42, 31, 59946, tzinfo=utc)),
        ),
    ]
