# Generated by Django 4.0.4 on 2022-05-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcashflow',
            name='name',
        ),
    ]
