# Generated by Django 4.0.4 on 2022-05-11 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0006_goal_goal_date_alter_changeinexpenses_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assumed_yearly_inflation',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 49, 33, 159876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 49, 33, 159400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 49, 33, 160457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='onetimeinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 49, 33, 161042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recurringinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 49, 33, 161542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 5, 49, 33, 158893, tzinfo=utc)),
        ),
    ]
