# Generated by Django 4.0.4 on 2022-05-12 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0008_alter_changeinexpenses_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcashflow',
            name='added_yearly_to_retirement',
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='workcashflow',
            name='amount_kept_in_savings',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='workcashflow',
            name='money_market_yearly_growth_rate',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='workcashflow',
            name='retirement_yearly_growth_rate',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='workcashflow',
            name='starting_retirement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 4, 10, 29, 752281, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 4, 10, 29, 751878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 4, 10, 29, 752781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='onetimeinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 4, 10, 29, 753240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recurringinvestment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 4, 10, 29, 753666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 4, 10, 29, 751383, tzinfo=utc)),
        ),
    ]
