# Generated by Django 4.1 on 2022-08-28 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0011_remove_recurringinvestment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 7, 41, 4, 256969, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 7, 41, 4, 256493, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 7, 41, 4, 257429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 7, 41, 4, 255857, tzinfo=datetime.timezone.utc)),
        ),
    ]
