# Generated by Django 4.1 on 2022-12-01 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarot_app', '0012_alter_changeinexpenses_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 3, 48, 854406, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 3, 48, 853787, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 3, 48, 855038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 3, 48, 852893, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('monetary_category', models.CharField(choices=[('INV', 'Investments'), ('RET', 'Retiremnt'), ('NET', 'Net Worth')], default='INV', max_length=200)),
                ('observed_amount', models.IntegerField()),
                ('observed_date', models.DateField(default=datetime.datetime(2022, 12, 1, 15, 3, 48, 855766, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
