# Generated by Django 4.1 on 2022-12-01 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0013_alter_changeinexpenses_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 7, 27, 979481, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 7, 27, 978311, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='monetary_category',
            field=models.CharField(choices=[('invested value', 'Investments'), ('retirement value', 'Retirement'), ('net worth', 'Net Worth')], default='invested value', max_length=200),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='observed_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 7, 27, 981984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 7, 27, 980646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 7, 27, 976707, tzinfo=datetime.timezone.utc)),
        ),
    ]
