# Generated by Django 4.1 on 2022-12-01 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0014_alter_changeinexpenses_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinexpenses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 38, 4, 418023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='changeinincome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 38, 4, 416868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='observed_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 38, 4, 420383, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dollar_value_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 38, 4, 419155, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workcashflow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 38, 4, 415249, tzinfo=datetime.timezone.utc)),
        ),
    ]
